/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompressorRouteImport } from './routes/compressor'
import { Route as CarroRouteImport } from './routes/carro'
import { Route as IndexRouteImport } from './routes/index'

const CompressorRoute = CompressorRouteImport.update({
  id: '/compressor',
  path: '/compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const CarroRoute = CarroRouteImport.update({
  id: '/carro',
  path: '/carro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carro' | '/compressor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carro' | '/compressor'
  id: '__root__' | '/' | '/carro' | '/compressor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarroRoute: typeof CarroRoute
  CompressorRoute: typeof CompressorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compressor': {
      id: '/compressor'
      path: '/compressor'
      fullPath: '/compressor'
      preLoaderRoute: typeof CompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carro': {
      id: '/carro'
      path: '/carro'
      fullPath: '/carro'
      preLoaderRoute: typeof CarroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarroRoute: CarroRoute,
  CompressorRoute: CompressorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
