/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompressorRouteImport } from './routes/compressor'
import { Route as CarroRouteImport } from './routes/carro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYuvexpayWebhookRouteImport } from './routes/api/public/yuvexpay-webhook'

const CompressorRoute = CompressorRouteImport.update({
  id: '/compressor',
  path: '/compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const CarroRoute = CarroRouteImport.update({
  id: '/carro',
  path: '/carro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYuvexpayWebhookRoute =
  ApiPublicYuvexpayWebhookRouteImport.update({
    id: '/api/public/yuvexpay-webhook',
    path: '/api/public/yuvexpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/carro': typeof CarroRoute
  '/compressor': typeof CompressorRoute
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/carro'
    | '/compressor'
    | '/api/public/yuvexpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/carro'
    | '/compressor'
    | '/api/public/yuvexpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/carro'
    | '/compressor'
    | '/api/public/yuvexpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CarroRoute: typeof CarroRoute
  CompressorRoute: typeof CompressorRoute
  ApiPublicYuvexpayWebhookRoute: typeof ApiPublicYuvexpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compressor': {
      id: '/compressor'
      path: '/compressor'
      fullPath: '/compressor'
      preLoaderRoute: typeof CompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carro': {
      id: '/carro'
      path: '/carro'
      fullPath: '/carro'
      preLoaderRoute: typeof CarroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yuvexpay-webhook': {
      id: '/api/public/yuvexpay-webhook'
      path: '/api/public/yuvexpay-webhook'
      fullPath: '/api/public/yuvexpay-webhook'
      preLoaderRoute: typeof ApiPublicYuvexpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CarroRoute: CarroRoute,
  CompressorRoute: CompressorRoute,
  ApiPublicYuvexpayWebhookRoute: ApiPublicYuvexpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
